org: thaiskotovicz
app: payroll-charts
service: payroll-charts

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi

plugins:
  - serverless-offline
  - serverless-openapi-documentation

custom:
  documentation:
    version: '1'
    title: 'Payroll Charts'
    description: 'API que lista o headcount e turnover por liderados diretos e indiretos'
    models:
      - name: "PayrollResponse"
        description: "Folha de pagamento"
        contentType: "application/json"
        schema: ${file(src/models/PayrollResponse.json)}
      - name: "HeadcountResponse"
        description: "Headcount"
        contentType: "application/json"
        schema: ${file(src/models/HeadcountResponse.json)}
      - name: "TurnoverResponse"
        description: "Turnover"
        contentType: "application/json"
        schema: ${file(src/models/TurnoverResponse.json)}

functions:
  getPayroll:
    handler: src/lambdas/getPayroll.handler
    events:
      - http:
          path: /api/v1/payroll
          method: get
          documentation:
            summary: "Folha de pagamento"
            description: "Lista a folha de pagamento completa"
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "A employees array with its informations and manager email"
                responseModels:
                  application/json: "PayrollResponse"
              - statusCode: 500
                description: "An error message request fails"

  getPayrollByManager:
    handler: src/lambdas/getPayrollByManager.handler
    events:
      - http:
          path: /api/v1/payroll/{email}
          method: get
          documentation:
            summary: "Folha de pagamento por líder"
            description: "Lista a folha de pagamento dos subordinados"
            pathParams:
              - name: "email"
                description: "Email do supervisor"
                schema:
                  type: "string"
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "A employees array with its informations and manager email"
                responseModels:
                  application/json: "PayrollResponse"
              - statusCode: 500
                description: "An error message request fails"

  getHeadcount:
    handler: src/lambdas/getHeadcount.handler
    events:
      - http:
          path: /api/v1/payroll/headcount/{email}
          method: get
          documentation:
            summary: "Headcount por líder"
            description: "Calcula o headcount por líder"
            pathParams:
              - name: "email"
                description: "Email do supervisor"
                schema:
                  type: "string"
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "A headcount array by month"
                responseModels:
                  application/json: "HeadcountResponse"
              - statusCode: 500
                description: "An error message request fails"

  getTurnover:
    handler: src/lambdas/getTurnover.handler
    events:
      - http:
          path: /api/v1/payroll/turnover/{email}
          method: get
          documentation:
            summary: "Turnover por líder"
            description: "Calcula o turnover por líder"
            pathParams:
              - name: "email"
                description: "Email do supervisor"
                schema:
                  type: "string"
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "A turnover array by month"
                responseModels:
                  application/json: "TurnoverResponse"
              - statusCode: 500
                description: "An error message request fails"
